### ISSUE TITLE
Sending memo before contact request is answered breaks encryption

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonLite#168]
![sdl-borken](https://user-images.githubusercontent.com/30298/85185826-b962fc80-b263-11ea-9733-2004b1cf4823.png)

**Comment by DenioD** [comment]
This is rly a little bit complicated atm for our users. We should disable the send button while waiting for the response of the contact request, and show a little message like "You can send a message after your partner response". 

Since this is our key exchange between Alice and Bob, we have to force the user to wait.

**Comment by leto** [comment]
@DenioD sounds groovy, we can "fix" this at the GUI layer. Since users can type out their message while they wait, it seems fine for now

**Comment by leto** [comment]
@DenioD we are enforcing the invariant that "Only contacts can send memos to each other", where Contact Requests are the initial "handshake" and have special handling because of that. This is good for me to explain in the whitepaper

**Comment by DenioD** [comment]
SDL will now only allow to send a message, if their is one incoming message from this contact (initial request). So this issue should be fixed :+1:

**Comment by leto** [comment]
@DenioD can you clarify, is this fixed in 1.3.9 or will it be in the next release?

**Comment by DenioD** [comment]
It's fixed and include in the next release (1.3.9)
