### ISSUE TITLE
Fastsync Link incorrect

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#51]
In SDA, I see this code :
<html><head/><body><p>Skips the most expensive checks during the initial block download. <a href="https://docs.silentdragon.co/using-silentdragon/#fastsync"><span style=" text-decoration: underline; color:#0000ff;">Learn More</span></a></p></body></html>

I think the web address "https://docs.silentdragon.co/using-silentdragon/#fastsync" is not correct.

**Comment by leto** [comment]
@gilardh this is correct, good find. Hush actually does not need that special feature which was added to ZecWallet, because ZEC mainnet is so large and takes so long to sync. So Hush does not have this feature, I deleted the code from SD and @DenioD should delete this code and translation stuff from SDL
