### ISSUE TITLE
Link incorrect to the explorer

### ISSUE THREAD

**Issue by gilardh** [MyHush/SilentDragonLite#52]
In SDA, I see this code :
            if (!txid.isEmpty()) {
                menu.addAction(QObject::tr("View on block explorer"), [=] () {
                    QString url;
                    if (Settings::getInstance()->isTestnet()) {
                        url = "https://explorer.testnet.z.cash/tx/" + txid;
                    } else {
                        url = "https://hush3.komodod.com/transactions/" + txid;
                    }
                    QDesktopServices::openUrl(QUrl(url));
                });

I think "https://explorer.testnet.z.cash/tx/" is not correct.

**Comment by leto** [comment]
@gilardh you are technically correct, but HUSH doesn't have a testnet or testnet explorer (we just spin up a new chain with KMD tools, as needed), so I knowingly left that code in SD and @DenioD has left it in SDL.

I would say this is a known issue. If we do have a testnet and testnet explorer one day, than we can update this URL. Otherwise, the `isTestnet()` will always be false for Hush, so that code is never run.

Thanks for your report!
